### ISSUE TITLE
Keymap key vs keycode

### ISSUE THREAD

**Issue by Zinston** [odoo-dev/jabberwock#123]
The keycode for `:` is `Period`. So doing `CTRL+<Period>` is indeed the same as doing `CTRL+:`  but weirdly while `CTRL+SHIFT+<Period>` executes the command I requested, if I change it to `CTRL+SHIFT+:` it does a `select all`.
Same kind of issue with `CTRL+;` that is unmappable: it refreshes the page.
These are probably related to the browser.

Also, impossible in the current implementation to map a shortcut using the `+` key without using its keycode.

**Comment by Goaman** [comment]
The current behavior is normal.

The key will never be ":" when you hit SHIFT with your keyboard.

The `key` in javascript is relative to the current "keyboard layout" of the user.

For instance there is no API no know when a user hit SHIFT, which `key` it would have been without the SHIFT.

**Comment by Zinston** [comment]
Wait what about the `CTRL++ `?

**Comment by Goaman** [comment]
This one will not work, I'm creating an issue for that one.

**Comment by Goaman** [comment]
https://github.com/odoo-dev/jabberwock/issues/124
