### ISSUE TITLE
Link Dialog does not completely disappear when clicking on save

### ISSUE THREAD

**Issue by dmo-odoo** [odoo-dev/jabberwock#171]
![Screenshot 2020-05-15 at 09 44 36](https://user-images.githubusercontent.com/8427726/82024851-b7b87e80-9690-11ea-8131-bf5b0271ec71.png)

The form is destroyed but the empty floating dialog stays.

cc @Zinston @Gorash

**Comment by Zinston** [comment]
Handled in #174
