### ISSUE TITLE
Link + enter

### ISSUE THREAD

**Issue by Goaman** [odoo-dev/jabberwock#187]
When hitting enter, the new format should not be a link.
Video https://youtu.be/5Lf9dSy7pZk

**Comment by dmo-odoo** [comment]
Wait. It should not be a link but it should be, say, bold or underline or italic ? All of them are modifiers.

**Comment by Goaman** [comment]
Seems fine for me.

**Comment by Goaman** [comment]
@sebgeelen

**Comment by sebgeelen** [comment]
should be fixed now since #197 is merged
