### ISSUE TITLE
Enter+char after font awesome duplicates font awesome

### ISSUE THREAD

**Issue by Zinston** [odoo-dev/jabberwock#198]
1. Press ENTER at end of Heading ending with font awesome
2. Press a character key
The font awesome is duplicated before the character.

https://drive.google.com/file/d/1jJ571YDAMa7cDoLbydCL7IY-4Ha_OlvF/view

**Comment by Zinston** [comment]
This should be fixed with #197 (by not preserving `Attributes`). The problem emerges because the font awesome classes are preserved after the paragraph break. They are then transfered to the new character.

**Comment by sebgeelen** [comment]
should be fixed now since #197 is merged
