### ISSUE TITLE
Karma memory leak

### ISSUE THREAD

**Issue by Zinston** [odoo-dev/jabberwock#90]
My computer doesn't have enough RAM so a memory leak is always a big problem. This reveals itself in a particularly excruciating way with Karma: I can't run the tests and Chrome's devtools at the same time.

Removing the line declaring the source map in the configuration file of Karma seems to fix the problem but then of course the source mapping is crappy.

**Comment by dmo-odoo** [comment]
There is something else which might be somewhat related. When we do `npm run test`, it seems there are two process fighting to run tests. One in the browser, and one in the terminal. @Goaman would it be possible to have something like `npm run karma` for the browser one and `npm run test` for the terminal one such that they do not fight for dominance anymore ?

**Comment by dmo-odoo** [comment]
I'm closing this issue since it seems to be fixed since https://github.com/odoo-dev/jabberwock/commit/11ae2fd7eeb1f69248bcda44c5233227e6c96f5c.
Feel tree to re-open it if further work is needed on that front.
